version: '3.8'

services:
  mongodb:
    image: mongo:latest # Usa la última versión de MongoDB
    container_name: mongodb-container
    restart: always
    ports:
      - "27017:27017" # Exponer MongoDB en el puerto 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER} # Usuario administrador
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS} # Contraseña del administrador
    volumes:
      - ./mongo:/data/db # Persistencia de datos

